# Generated by Django 4.1.7 on 2023-04-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
