# Generated by Django 4.1.7 on 2023-04-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_review',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='review_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
